import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import react from '@astrojs/react';
import icon from 'astro-icon';
import sitemap from '@astrojs/sitemap';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  site: 'https://auxodata.com',
  base: '/',
  output: 'static',
  build: {
    assets: '_astro',
    inlineStylesheets: 'auto',
  },
  compressHTML: true,
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },
  image: {
    service: { entrypoint: 'astro/assets/services/sharp' },
    remotePatterns: [{ protocol: 'https' }],
  },
  vite: {
    optimizeDeps: {
      include: ['embla-carousel', 'sharp', 'astro-icon'],
      exclude: ['@astrojs/react'],
    },
    build: {
      sourcemap: false,
      target: 'esnext',
      cssCodeSplit: true,
      minify: 'terser',
      chunkSizeWarningLimit: 500,
      terserOptions: {
        compress: {
          drop_debugger: true,
          drop_console: true,
          pure_funcs: ['console.log', 'console.info', 'console.debug'],
        },
        mangle: { safari10: true },
      },
      rollupOptions: {
        maxParallelFileOps: 3,
        output: {
          chunkFileNames: '_astro/[name]-[hash].js',
          assetFileNames: '_astro/[name]-[hash].[ext]',
          experimentalMinChunkSize: 1500,
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('embla-carousel')) return 'ui-vendor';
              if (id.includes('astro-icon') || id.includes('@iconify')) return 'icons';
              if (id.includes('react') || id.includes('react-dom')) return 'react-vendor';
              if (id.includes('@emailjs')) return 'emailjs';
              if (id.includes('lenis')) return 'lenis';
            }
            if (id.includes('src/data/content/services/data')) return 'services-data';
          },
        },
      },
    },
    css: { devSourcemap: false },
    esbuild: {
      legalComments: 'none',
      treeShaking: true,
      minifyIdentifiers: true,
      minifySyntax: true,
      minifyWhitespace: true,
    },
    logLevel: 'warn',
    resolve: { alias: { '@': path.resolve(__dirname, './src') } },
  },
  integrations: [
    react(),
    tailwind({
      applyBaseStyles: false,
    }),
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en-US',
        },
      },
    }),
    icon({
      include: {
        'simple-icons': [
          'python',
          'r',
          'amazonaws',
          'microsoftazure',
          'googlecloud',
          'snowflake',
          'databricks',
          'tableau',
          'powerbi',
          'looker',
          'metabase',
          'apachesuperset',
          'dbt',
          'apacheairflow',
          'apachespark',
          'apachekafka',
          'tensorflow',
          'pytorch',
          'huggingface',
          'scikitlearn',
          'mlflow',
          'jupyter',
          'pandas',
          'numpy',
          'postgresql',
          'mongodb',
          'redis',
          'elasticsearch',
          'git',
          'docker',
          'kubernetes',
          'grafana',
          'prometheus',
          'influxdb',
          'cockroachlabs',
          'apachecassandra',
          'flask',
        ],
        mdi: [
          'ab-testing',
          'account-group',
          'account-group-outline',
          'account-tie',
          'alert-circle',
          'arrow-right',
          'atom',
          'auto-fix',
          'book-open',
          'book-open-variant',
          'brain',
          'briefcase',
          'bullseye',
          'calendar-clock',
          'calendar-outline',
          'cart',
          'cellphone-cog',
          'chart-areaspline',
          'chart-box',
          'chart-donut-variant',
          'chart-line',
          'chart-line-variant',
          'chart-timeline-variant',
          'check-bold',
          'check-circle',
          'check-circle-outline',
          'check-decagram',
          'checkbox-marked',
          'chevron-down',
          'clipboard-list',
          'clipboard-text-outline',
          'clock-check-outline',
          'clock-outline',
          'close',
          'cog-play',
          'cog-sync',
          'cogs',
          'compass-outline',
          'cookie',
          'crosshairs-gps',
          'crystal-ball',
          'database-cog',
          'database-plus',
          'database-search',
          'domain',
          'earth',
          'email-outline',
          'file-chart',
          'file-document',
          'file-document-multiple',
          'file-send',
          'file-tree',
          'finance',
          'flag-checkered',
          'format-list-bulleted',
          'function-variant',
          'gavel',
          'hammer-wrench',
          'handshake',
          'head-lightbulb',
          'home',
          'information-outline',
          'layers',
          'lightbulb',
          'lightbulb-on',
          'linkedin',
          'magnify-scan',
          'map-marker',
          'map-marker-outline',
          'map-marker-path',
          'map-search',
          'monitor-dashboard',
          'monitor-eye',
          'moon-waning-crescent',
          'package-variant',
          'palette',
          'palm-tree',
          'pipe',
          'quality-high',
          'robot',
          'rocket-launch',
          'school',
          'send',
          'server-network',
          'shield-account',
          'shield-check',
          'shield-check-outline',
          'shield-lock',
          'shield-star',
          'shopping',
          'star-circle',
          'target',
          'telescope',
          'text-recognition',
          'toolbox',
          'trending-up',
          'tune',
          'twitter',
          'view-dashboard-variant',
          'waves',
          'web',
          'white-balance-sunny',
        ],
      },
    }),
  ],
});

