export const BREAKPOINTS = {
  SM: 640,
  MD: 768,
  LG: 1024,
} as const;

export const SCROLL_THRESHOLDS = {
  FLOATING_BUTTON_SHOW: 300,
  FLOATING_BUTTON_HIDE_INITIAL: 1500,
  FLOATING_BUTTON_ANDROID_DELAY: 50,
  SCROLL_INDICATOR_THRESHOLD: 10,
} as const;

export const SCROLL_OFFSETS = {
  DEFAULT: 80,
} as const;
